import fs from 'fs';
import md from 'markdown-it';
import Head from 'next/head';
import styles from '../../styles/Home.module.css'

export async function getStaticPaths() {
    const ids = [];
    for (let i = 1; i <= 10; i++) { ids.push(i); };

    const paths = ids.map((i) => ({
        params: { id: i.toString() }
    }))

    return { paths, fallback: false };
};

export async function getStaticProps ({ params }) {
    
    const fileContents = fs.readFileSync(`public/responses/${params.id}.md`, {encoding:'utf8', flag:'r'});
    console.log(fileContents)
    
    return {
        props: {
            id: params.id,
            content: fileContents
        }
    }
};

export default function Responses(params) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Take Home!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>
                    Question {params.id}
                </h1>
                <div dangerouslySetInnerHTML={{ __html: md().render(params.content) }} />
            </main>
        </div>
    )
};