import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {

    //efficiency at its greatest
    let numbers = [];
    for (let i = 1; i <= 10; i++) { numbers.push(i); };
    
    return (
        <div className={styles.container}>
            <Head>
                <title>Take Home!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Take<span>Home</span>
                </h1>
                
                <p className={styles.description}>
                    My responses to the Vercel takehome. Used <code>create-next-app</code> for simplicity.
                </p>

                <div className={styles.grid}>
                    {
                        numbers.map((num) => {
                            console.log(num)
                            return (
                                <a href={`responses/${num}`} className={styles.card}>
                                    <h2>Question {num}</h2>
                                </a>
                            )
                        })
                    }
                </div>
            </main>

            <footer className={styles.footer}>
                <a href="https://piemadd.com/">piero waz here</a> 
            </footer>
        </div>
    )
}
